####
# Full version of build workflow
#
# This is a full version of build workflow for build and release:
# - test and build native application
# - build and store as build artifacts Android and iOS Application
# - for releases (git tag) upload a build artifact to Google Play and Apple TestFlight
# - send slack notification
on:
  push:
    branches:
      - develop
    tags:
      - "*"
jobs:
  build:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "10.15.3"
          registry-url: "https://registry.npmjs.org"

      #
      # Native Application
      #
      - run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
        working-directory: energylink-connect2-app

      - run: npm run test
        env:
          CI: 1
        working-directory: energylink-connect2-app

      - name: Decrypt .env
        run: openssl aes-256-cbc -d -a -salt -k '${{ secrets.ENVFILE_PASSWORD }}' -in .env.enc -out .env
        working-directory: energylink-connect2-app

      - run: npm run build
        working-directory: energylink-connect2-app

      #
      # Configure environment for iOS and Android
      #
      - uses: actions/setup-java@v1
        with:
          java-version: 8

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.4"

      - name: Install RubyGems
        run: bundle install --jobs 4 --retry 3

      - name: Install Cordova
        run: |
          npm install
          npm install -g cordova@9.0.0
          npm rebuild node-sass

      - name: Prepare cordova build for Android and iOS
        run: |
          npx phonegap prepare android
          npx phonegap prepare ios

      - name: Configure credentials
        run: |
          echo "${{ secrets.GOOGLE_PLAY_UPLOAD_KEYSTORE }}" | base64 -d > upload-keystore.jks
          echo "${{ secrets.GOOGLE_PLAY_API_KEY }}" | base64 -d > google-api.json

      #
      # Android Application
      #
      - name: Build Android Application
        run: bundle exec fastlane android build
        env:
          KEYSTORE_PASSWORD: ${{ secrets.GOOGLE_PLAY_UPLOAD_KEYSTORE_PASSWORD }}

      - uses: actions/upload-artifact@v1
        with:
          name: Android
          path: platforms/android/app/build/outputs/apk/release/app-release.apk

      #
      # iOS Application
      #
      - name: Build iOS Application
        run: bundle exec fastlane ios build
        env:
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}

      - uses: actions/upload-artifact@v1
        with:
          name: iOS
          path: platforms/ios/build/device/EnergyLinkConnect2.ipa

      #
      # Release Android and iOS Application
      #
      - name: Upload build to Google Play store
        run: bundle exec fastlane android release
        if: startsWith(github.ref, 'refs/tags/')

      - name: Upload build to Apple TestFlight
        run: bundle exec fastlane ios release
        if: startsWith(github.ref, 'refs/tags/')
        env:
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}

      #
      # Slack Notification
      #
      - name: Calculate GIT branch name
        run: |
          export BRANCH_NAME=${GITHUB_REF#refs/heads/}
          export BRANCH_NAME=${BRANCH_NAME#refs/tags/}
          echo "::set-env name=BRANCH_NAME::$BRANCH_NAME"

      - name: Send slack notification
        uses: hbfernandes/slack-action@1.0
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        with:
          args: |
            {
              "channel": "cm2-builds",
              "text": "New release is available",
              "as_user": true,
              "attachments": [{
                "color": "good",
                "fields": [{
                    "title": "Revision",
                    "value": "${{ env.BRANCH_NAME }}",
                    "short": true
                  },
                  {
                    "title": "Build Artifacts",
                    "value": "<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|Open>",
                    "short": true
                  }
                ]
              }]
            }
